// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Platforms.Ios.Views;
using SampleMvvmcrossApp.Core.ViewModels;
using UIKit;

namespace SampleMvvmcrossApp.iOS.Cell.Authentication
{
	[MvxFromStoryboard]
	public partial class LoginStoryboard : MvxViewController<Loginview>
	{
		public LoginStoryboard (IntPtr handle) : base (handle)
		{
		}
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

        }
    }
}
