// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Platforms.Ios.Views;
using SampleMvvmcrossApp.Core.ViewModels.Main;
using UIKit;

namespace SampleMvvmcrossApp.iOS.Cell.Authentication
{
	public partial class SignupViewControl : MvxViewController<Signupview>
    {
		public SignupViewControl (IntPtr handle) : base (handle)
		{
		}
	}
}
