// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Platforms.Ios.Views;
using SampleMvvmcrossApp.Core.ViewModels;
using UIKit;

namespace SampleMvvmcrossApp.iOS.Cell
{
    [MvxFromStoryboard]

    public partial class XamViewController : UIViewController
	{
		public XamViewController (IntPtr handle) : base (handle)
		{
		}
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            // Perform any additional setup after loading the view, typically from a nib.
        }


    }
}
