// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Platforms.Ios.Presenters.Attributes;
using MvvmCross.Platforms.Ios.Views;
using SampleMvvmcrossApp.Core.ViewModels;
using UIKit;

namespace SampleMvvmcrossApp.iOS.Cell
{
    [MvxFromStoryboard("XAmStoryboard")]
    [MvxTabPresentation(WrapInNavigationController = true, TabName = "XamViewController")]

    public partial class XamViewController : UIViewController
	{
		public XamViewController (IntPtr handle) : base(nameof(XamViewController), null)
        {
		}
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            // Perform any additional setup after loading the view, typically from a nib.
        }


    }
}
